#list of analysis levels in the bids app
analysis_levels: &analysis_levels
 - participant

#mapping from analysis_level to set of target rules or files
targets_by_analysis_level:
  participant:
    - 'all'

pybids_inputs:
  mri:
    filters:
      suffix: 'T2starw'
      extension: 'nii.gz'
      datatype: 'anat'
      desc: 'preproc'
    wildcards:
      - subject
      - session


#configuration for the command-line parameters to make available
parse_args:
  --bids_dir:
    help: "Path to the BIDS dataset directory"
    type: str
    required: True

  --output_dir:
    help: "Path to the output directory"
    type: str
    required: True

  --target_template:
    help: "Target template to register mri-atlas to (default: %(default)s)"
    default: ABAv3

  --template_path:
    help: "Path to the initial mean image for first-pass registration"
    type: str
    required: True

  --template_path_target:
    help: "Path to the target template NIfTI image"
    type: str
    required: True

  --skip-bids-validation:
    help: |
      Skip validation of BIDS dataset. BIDS validation is performed by
      default using the bids-validator plugin (if installed/enabled) or with the pybids
      validator implementation (if bids-validator is not installed/enabled).
    dest: "plugins.validator.skip"
    action: "store_true"
    default: False


#--- workflow specific configuration ---

bids_dir: null
output_dir: null
target_template: ABAv3
template_path: null
template_path_target: null
